version: "3"
services:
  mysql:
    image: mysql:5.7.32
    environment:
      MYSQL_ROOT_PASSWORD: 'pass'
    ports:
      - '3306:3306'
    volumes:
      - mysql:/var/lib/mysql
      - ./docker/mysql/charset.cnf:/etc/mysql/conf.d/charset.cnf

  php:
    build: .
    ports:
      - '8000:8000'
    environment:
      TZ: 'Asia/Tokyo'
      APP_DEFAULT_LOCALE: ja-JP
      DATABASE_URL: mysql://root:pass@mysql:3306/project?encoding=utf8
    command: /bin/sh -c "php artisan serve"
    volumes:
      - .:/usr/src/app
    links:
      - mysql
    depends_on:
      - mysql

volumes:
  mysql: